# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "gusztavvargadr/windows-server-2022-standard"
  config.vm.box_version = "2102.0.2409"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.network "forwarded_port", guest: 5671, host: 55671
  config.vm.network "forwarded_port", guest: 5672, host: 55672
  config.vm.network "forwarded_port", guest: 15672, host: 55673
end
